spring.application.name=springboot-llm-learning

openai.api-key=${OPENAI_API_KEY}
openai.base-url=https://api.openai.com

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.7
